exp_name: vit_tiny

attention_probs_dropout_prob: 0.0
hidden_dropout_prob: 0.2
num_hidden_layers: 6
hidden_size: 96
image_size: 32
initializer_range: 0.02
mlp_ratio: 4
num_attention_heads: 4
num_channels: 3
num_classes: 10
patch_size: 4
qkv_bias: true
# use_faster_attention: true

init_lr: 0.001
epochs: 100
batch_size: 1
save_model_every: 5
init_ckpt: experiments\vit_tiny\model_final.pt